# Generated by Django 5.2.4 on 2025-07-26 20:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome comercial ou genérico do medicamento', max_length=200, verbose_name='Nome do Medicamento')),
                ('principio_ativo', models.CharField(help_text='Substância ativa do medicamento', max_length=200, verbose_name='Princípio Ativo')),
                ('concentracao', models.CharField(help_text='Concentração do medicamento (ex: 500mg, 10ml)', max_length=100, verbose_name='Concentração')),
                ('tipo', models.CharField(choices=[('comprimido', 'Comprimido'), ('capsula', 'Cápsula'), ('liquido', 'Líquido'), ('injecao', 'Injeção'), ('pomada', 'Pomada'), ('gotas', 'Gotas'), ('spray', 'Spray'), ('outro', 'Outro')], help_text='Forma farmacêutica do medicamento', max_length=20, verbose_name='Tipo')),
                ('fabricante', models.CharField(blank=True, help_text='Laboratório fabricante do medicamento', max_length=200, null=True, verbose_name='Fabricante')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras do medicamento', max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional do medicamento', null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o medicamento está disponível para prescrição', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo do paciente', max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('data_nascimento', models.DateField(help_text='Data de nascimento do paciente', verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('telefone_contato', models.CharField(blank=True, help_text='Telefone para contato de emergência', max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo do paciente ou responsável', null=True, verbose_name='Endereço')),
                ('observacoes_medicas', models.TextField(blank=True, help_text='Observações importantes sobre o estado de saúde do paciente', null=True, verbose_name='Observações Médicas')),
                ('data_admissao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora de admissão no asilo', verbose_name='Data de Admissão')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o paciente ainda está no asilo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='PrescricaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(help_text='Dosagem prescrita (ex: 1 comprimido, 5ml)', max_length=100, verbose_name='Dosagem')),
                ('frequencia', models.CharField(choices=[('1x_dia', '1x ao dia'), ('2x_dia', '2x ao dia'), ('3x_dia', '3x ao dia'), ('4x_dia', '4x ao dia'), ('6x_dia', '6x ao dia'), ('8x_dia', '8x ao dia'), ('12h', 'A cada 12 horas'), ('8h', 'A cada 8 horas'), ('6h', 'A cada 6 horas'), ('4h', 'A cada 4 horas'), ('sos', 'Se necessário (SOS)'), ('personalizada', 'Frequência personalizada')], help_text='Frequência de administração', max_length=20, verbose_name='Frequência')),
                ('frequencia_personalizada', models.CharField(blank=True, help_text="Descrição da frequência quando selecionada 'personalizada'", max_length=200, null=True, verbose_name='Frequência Personalizada')),
                ('horarios_administracao', models.JSONField(blank=True, help_text='Lista de horários para administração (formato JSON)', null=True, verbose_name='Horários de Administração')),
                ('data_inicio', models.DateField(help_text='Data de início do tratamento', verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim do tratamento (se aplicável)', null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('finalizado', 'Finalizado')], default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a prescrição', null=True, verbose_name='Observações')),
                ('medico_responsavel', models.CharField(help_text='Nome do médico que prescreveu o medicamento', max_length=200, verbose_name='Médico Responsável')),
                ('enfermeiro_cadastro', models.CharField(help_text='Nome do enfermeiro que cadastrou a prescrição', max_length=200, verbose_name='Enfermeiro Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='api.medicamento', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='api.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Prescrição de Medicamento',
                'verbose_name_plural': 'Prescrições de Medicamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_prevista', models.DateTimeField(help_text='Data e hora prevista para administração', verbose_name='Data/Hora Prevista')),
                ('data_hora_administracao', models.DateTimeField(blank=True, help_text='Data e hora real da administração', null=True, verbose_name='Data/Hora de Administração')),
                ('status', models.CharField(choices=[('administrado', 'Administrado'), ('nao_administrado', 'Não Administrado'), ('recusado', 'Recusado pelo Paciente')], default='administrado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a administração', null=True, verbose_name='Observações')),
                ('enfermeiro_responsavel', models.CharField(help_text='Nome do enfermeiro que administrou o medicamento', max_length=200, verbose_name='Enfermeiro Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_administracao', to='api.prescricaomedicamento', verbose_name='Prescrição')),
            ],
            options={
                'verbose_name': 'Registro de Administração',
                'verbose_name_plural': 'Registros de Administração',
                'ordering': ['-data_hora_prevista'],
            },
        ),
    ]
